### ISSUE TITLE
split Integer into Int32 and Uint32?

### ISSUE THREAD

**Issue by dherman** [rustbridge/neon#16]
The `v8::Value` predicates include `IsInt32` and `IsUint32` which suggests that maybe their value tagging scheme distinguishes the two? If so then there ought to be separate `Int32` and `Uint32` types. Need to investigate.

**Comment by bnoordhuis** [comment]
> which suggests that maybe their value tagging scheme distinguishes the two?

`IsUint32()` returns true when the value is either a tagged integer or a boxed double that can be losslessly converted to uint32_t.

`IsInt32()` more or less works the same way except that on 64 bits architectures the tagged value always fits in a word (although it can still end up getting boxed so you still have to check the type tag.)

**Comment by dherman** [comment]
IIUC, this means it's not a great idea to try to distinguish the types, since the distinction doesn't carry strong performance promises. Closing for now.
