### ISSUE TITLE
Post install in new project fails on Linux

### ISSUE THREAD

**Issue by commandline** [rustbridge/neon#23]
Followed the suggestion of using neon new to explore a simple hello world starter project. Running npm install, the post install step is failing due to an error from ld:
```
Compiling my-project v0.1.0 (file:///home/cmdln/src/git/my-project)
note: link against the following native artifacts when linking against this static library
note: the order and any duplication can be significant on some platforms, and so may need to be preserved
note: library: dl
note: library: pthread
note: library: gcc_s
note: library: rt
note: library: c
note: library: m
ACTION binding_gyp_my_project_target_shared_lib ../target/release/libmy_project.so
/usr/bin/ld: -f may not be used without -shared
collect2: error: ld returned 1 exit status
my_project.target.mk:26: recipe for target '../target/release/libmy_project.so' failed
make: *** [../target/release/libmy_project.so] Error 1
make: Leaving directory '/home/cmdln/src/git/my-project/build'
```

**Comment by codearoni** [comment]
The readme states that Neon only works on OS X at this time.

**Comment by commandline** [comment]
Yes, I know but the IRC channel has been discussing a PR to expand support to Linux.

**Comment by codearoni** [comment]
As an Ubuntu user, I would love aforementioned PR. If getting Neon running on Linux is as simple as making the postInstall conditional to the OS, it seems fairly straightforward, but I digress (I'm not an expert on the matter).

**Comment by dherman** [comment]
@commandline I just landed Linux support a couple hours ago. Can you update to neon-cli 0.1.2 and try again for me?

**Comment by dherman** [comment]
Should be fixed, so I'm closing this, but do let me know if you still have trouble. Thanks!

**Comment by commandline** [comment]
Yep, confirmed it is fixed--thanks @dherman!
