### ISSUE TITLE
need acceptance test for hyphenated project name

### ISSUE THREAD

**Issue by KenanSulayman** [rustbridge/neon#28]
Hi,

just a quick bug report - when creating a project with name that includes a minus, it will be put unsanitized into the source: `some-project` will result in `NODE_MODULE(some-project, __neon_main__);`

Cheers

**Comment by dherman** [comment]
This should be fixed now, but needs a test.

**Comment by dherman** [comment]
Oops, this issue belongs in neon-cli. Closing here; refiled as rustbridge/neon-cli#19.
