### ISSUE TITLE
Value, Object, Any renamings

### ISSUE THREAD

**Issue by dherman** [rustbridge/neon#36]
Looking at the API docs makes it clear that the traits *really* want to have the names Value and Object. And I came up with the "SomeObject" nomenclature for the root of the Object type hierarchy. So there should be a consistent nomenclature for root types in the type hierarchy, like SomeValue and SomeObject. I'm not in love with Some- as the prefix, so maybe we can come up with something better.

Also, neon::buffer should get moved under neon::value. Should we mirror the type hierarchy in a module hierarchy? Like neon::value::object::{Array, Object} etc, and neon::value::object::typed_array::Uint8Array etc?

**Comment by dherman** [comment]
A set of constraints I think are worth trying to satisfy in the naming:

* avoid painful collisions with common Rust abstractions, in particular Result and String
* different names for Object type vs Object trait
* different names for Value type vs Value trait
* any boilerplate prefixes of names should be short
* naming convention for value tags should hew closely to JS naming conventions (e.g. SomeObject isn't great since it's not a familiar JS convention)

**Comment by dherman** [comment]
Here's a proposed set of names. I think I'll try this out in a PR.

**Result**

* neon::vm::VmResult<T>
* neon::vm::JsResult<T>

**JS Values**

* neon::js::JsArray
* neon::js::JsBoolean
* neon::js::JsFunction
* neon::js::JsInteger
* neon::js::JsNull
* neon::js::JsNumber
* neon::js::JsObject
* neon::js::JsString
* neon::js::JsUndefined
* neon::js::JsValue

**JS Traits**

* neon::js::Object
* neon::js::Value

**JS Typed Arrays**

* neon::js::binary::JsUint8Array

**JS Errors**

* neon::js::error::JsError

**Comment by dherman** [comment]
An alternative would be to go ahead and call them e.g. `neon::js::String` and recommend referring to them with qualified paths like `js::String`, but then we'd have to come up with alternative names for the `Object` and `Value` traits. The Value trait could _maybe_ be `Js`, but what about `Object`?

**Comment by kjvalencik** [comment]
It would also be nice to have a specialized version of `v8::Buffer` that is used to pack / unpack a `Box` pointer.  `Buffer::new` allows you to specify a raw pointer and a callback for a destructor.

This way we could have way to pass structs back and forth across the boundary. Simple example with explicit bindings:


https://github.com/kjvalencik/hello-rust-js/blob/0c00f116862c3c2d26a5bfcf5101004dfe0b8e8c/src/binding.cc#L16-L19
https://github.com/kjvalencik/hello-rust-js/blob/0c00f116862c3c2d26a5bfcf5101004dfe0b8e8c/src/lib.rs#L29-L31

**Comment by Qard** [comment]
@kjvalencik `v8::External` is the more "correct" way to pass something like that around.

**Comment by kjvalencik** [comment]
@Qard Would `v8::Persistent` be a good option to have a GC callback to free?

**Comment by kjvalencik** [comment]
@Qard What is the correct way to get a GC callback to free the external resource on `v8::External`?
