### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by davidblewett** [rustbridge/neon#40]
Just an FYI, but the name `neon` has been around for a long while for this project: http://www.webdav.org/neon/ .

**Comment by Dashed** [comment]
@davidblewett Are you suggesting `neon` (this project) to be renamed to something else? Rust (the language) share the same name as the video game: https://en.wikipedia.org/wiki/Rust_(video_game)
Folks are smart enough to tell the difference.

**Comment by dherman** [comment]
Thanks for the heads-up. I don't want to step on anyone's toes, but I think there's room for software projects in significantly difference spaces to have the same name. Note that there's already another [neon project](https://www.npmjs.com/package/neon) in npm as well, so this is certainly not the first. I appreciate your bringing this to my attention, and I'll close for now.
