### ISSUE TITLE
safe custom JS objects embedding Rust data

### ISSUE THREAD

**Issue by dherman** [rustbridge/neon#44]
To avoid people using unsafe raw pointers like [v8::External](http://izs.me/v8-docs/classv8_1_1External.html) or [stashing pointers as integers in buffers](https://github.com/dherman/unsafe-greeter), there should be a safe way to create custom objects that own a boxed pointer to a Rust data structure. Some constraints:

* **No tracing.** We don't currently have the language infrastructure in Rust to integrate with a GC with custom tracing logic for data structures, so JS data can't wrap Rust data that wraps more JS data.
* **Finalization.** We'll need to associate a finalizer with all objects of custom types to deallocate the owned Rust data.
* **Branding.** We have to be able to reliably detect instances of these custom types, so that we know whether or not it's safe to look for the private pointer.

**Comment by dherman** [comment]
The mechanism we can use for hidden properties is v8::ObjectTemplate::{[New](https://github.com/v8/v8/blob/master/include/v8.h#L4618), [SetInternalFieldCount](https://github.com/v8/v8/blob/master/include/v8.h#L4770)} and v8::Object::{[GetAlignedPointerFromInternalField](https://github.com/v8/v8/blob/master/include/v8.h#L2838), [SetAlignedPointerFromInternalField](https://github.com/v8/v8/blob/master/include/v8.h#L2851)}.

The mechanism we can use to prevent tracing is to restrict the Rust API to requiring the owned Rust data to be bounded by the `'static` lifetime.

I'm not sure what the v8 finalization API is yet but I'll dig.

I'm also not sure what the v8 approach to object branding is. It must exist since there are all sorts of distinctly branded object types on the web that expose JS predicates to check for the brand. I'll have to keep digging on that too.

**Comment by kjvalencik** [comment]
I think JS data inside a JS wrapped struct could be safe as long as it uses a persistent handle. Persistent handles require an explicit disposer call and update their internal pointer on GC.

These are often used when you need to pass a callback function off into something async.

**Comment by dherman** [comment]
Forgot to mention: the rust api for the JS object type would implement Lock so you can get a borrowed reference to the internal rust data by locking the JS object.

**Comment by dherman** [comment]
@kjvalencik I think persistent handles are probably pretty easy to expose safely but too leak-prone to be the common case API (because you have to explicitly release them). I think we can do an API that used a finalizer to automatically release Rust data. But it's probably worth experimenting with both -- they may both serve different use cases.

**Comment by dherman** [comment]
Some progress from digging through V8 docs and mailing list threads: looks like the standard way to check if an object is of a particular type is to create it with a FunctionTemplate and use FunctionTemplate#HasInstance. Sadly it looks like the leaner ObjectTemplate doesn't have such functionality.

A tricky bit to figure out is how and when to allocate a user-defined FunctionTemplate since its lifetime is tied to the implicit v8::Context. Neon has no tracking of this, at least currently. (I hope the answer isn't threading another lifetime variable through all APIs!)

**Comment by dherman** [comment]
Basic shape of what the UX might look like for defining a class:

https://gist.github.com/dherman/18efdc5e6c342513e46b

**Comment by dherman** [comment]
Fixed in #58.
