### ISSUE TITLE
add value method to JsNumber and JsBoolean

### ISSUE THREAD

**Issue by dherman** [rustbridge/neon#48]
This is a good starter bug: you should be able to copy [what I did to add JsInteger::value()](https://github.com/rustbridge/neon/commit/8e5663d7550d6e2b47f6f2c13e17dce44fac3bee) to add analogous methods to JsNumber and JsBoolean. You'll need to use the [v8::Number](http://v8.paulfryzel.com/docs/master/classv8_1_1_number.html) and [v8::Boolean](http://v8.paulfryzel.com/docs/master/classv8_1_1_boolean.html) APIs in the implementation.

**Comment by msvbg** [comment]
Didn't see that you opened an issue for this :) It seemed like an obvious next step so I went ahead and did it in #49
