### ISSUE TITLE
JsString::new return Result instead of Option

### ISSUE THREAD

**Issue by chpio** [rustbridge/neon#54]
Hi,

i think we should use `Result` as the return value for `JsString::new`. That way we could 1. return a meaningful error 2. use `try!`

[click](https://github.com/rustbridge/neon/blob/master/src/internal/js/mod.rs#L297-L331)

ps: im a rust noob, so sorry for that if there is a real reason against `Result`

**Comment by dherman** [comment]
@chpio Does `JsString::new_or_throw` do what you want? The name is admittedly ugly -- is this a naming issue? Or is there something about `new_or_throw` that isn't what you're looking for?

**Comment by chpio** [comment]
sorry, im stupid
