### ISSUE TITLE
overload indexing for arrays and objects

### ISSUE THREAD

**Issue by dherman** [rustbridge/neon#8]
Would be great to be able to write:

```rust
array[0] = scope.integer(17);
```

and possibly even:

```rust
object["foo"] = scope.integer(42);
```

**Comment by eddyb** [comment]
Requires the hypothetical `IndexAssign`/`IndexSet` (and you also want `IndexGet` for `let x = array[0];`).

**Comment by dherman** [comment]
I take it by "hypothetical" this doesn't exist yet. I'll reopen if/when it happens.
