### ISSUE TITLE
Support path for v5 & v6

### ISSUE THREAD

**Issue by jsonnull** [rustbridge/neon#88]
Neon's readme states that the current supported node is v4 with v5 in the works.

What needs to be done to get neon working with node v5 and v6? Where do you need help?

**Comment by dherman** [comment]
Good catch thanks! Our CI is now testing on v4 - v6 and we'll try to keep up with the latest stable, so I updated the readme.

**Comment by jsonnull** [comment]
Awesome, thanks!
